version: "2"

# See explanation of linters at https://golangci-lint.run/usage/linters/
linters:
  default: none
  enable:
    - bodyclose
    - forbidigo
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - appendAssign # Too many false positives
        - assignOp # Maybe worth adding, but likely not worth the noise
        - commentFormatting # No strong benefit
        - deprecatedComment # Unnecessary
        - exitAfterDefer # Only occurs in auxiliary tools
        - ifElseChain # Noisy for not much gain
        - singleCaseSwitch # Noisy for not much gain
    govet:
      disable:
        - composites
  exclusions:
    # Exclude bodyclose lint from tests because leaking connections in tests
    # is a non-issue, and checking that adds unnecessary noise
    rules:
      - linters:
          - bodyclose
        path: _test\.go

formatters:
  enable:
    - goimports
